spring:
  application:
    name: msi
  profiles:
    active: @profileActive@
  mvc:
    pathmatch:
      # fix [Failed to start bean 'documentationPluginsBootstrapper'; nested exception is java.lang.NullPointerException]
      # issues https://github.com/springfox/springfox/issues/3462#issuecomment-978707909
      matching-strategy: ant_path_matcher

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  global-config:
    banner: false
